ALTER TABLE orderitem DROP COLUMN orderinfo_code;

--orderinfo_seq 삭제

ALTER TABLE orderinfo MODIFY orderinfo_code VARCHAR2(20);

ALTER TABLE orderitem ADD ORDERINFO_CODE VARCHAR2(20) NOT NUll;

ALTER TABLE ORDERITEM
ADD CONSTRAINT ORDERITEM_ORDERINFO_CODE_FK FOREIGN KEY(ORDERINFO_CODE)
REFERENCES ORDERINFO(ORDERINFO_CODE);

alter table orderitem drop CONSTRAINT ORDERITEM_ORDERINFO_CODE_FK;