ALTER TABLE ORDERITEM DROP COLUMN CART_CODE;  --orderitem cart_code 컬럼 삭제

ALTER TABLE ORDERITEM DROP COLUMN ITEM_CATEGORY;   --orderitem ITEM_CATEGORY 대신 ITEM_NAME 추가

ALTER TABLE ORDERITEM ADD ITEM_NAME VARCHAR2(50) NOT NULL;

create SEQUENCE orderItem_seq;