CREATE TABLE DELIVERY_INFO
(
DELIVERY_INFO_CODE NUMBER(10,0) NOT NULL, --배송 상태 전달해줄 ID
DELIVERY_INFO_STATUS VARCHAR2(10) NOT NULL, --배송중 배송완료 배송지연 배송실수 배송장애 
DELIVERY_INFO_COMPANY VARCHAR2(30) NOT NULL, --30 배송하기좋은날(SHIPNERGY) 제일 김
DELIVERY_INFO_INVOICE_NUMBER VARCHAR2(30) NOT NULL,  -- 운송장번호
DELIVERY_INFO_START_TIME DATE, --배송 상태 시작시간
DELIVERY_INFO_END_TIME DATE, -- 배송 상태 종료시간
ORDERINFO_CODE NUMBER(10,0) NOT NULL,
PRIMARY KEY (DELIVERY_INFO_CODE),
FOREIGN KEY (ORDERINFO_CODE) REFERENCES ORDERINFO(ORDERINFO_CODE)
);

ALTER TABLE ORDERINFO ADD DELIVERY_INFO_CODE NUMBER(10,0) NOT NULL;

저는 오더인포에 데이터가 있어서 NULL로 했습니다. 없으시면 NOT NULL로 해주세요 그게 맞습니다.
만약 있으시다면 밑에 쿼리문으로 해주세요

ALTER TABLE ORDERINFO ADD DELIVERY_INFO_CODE NUMBER(10,0) NULL;

ALTER TABLE ORDERINFO
ADD CONSTRAINT DELIVERY_FK FOREIGN KEY (DELIVERY_INFO_CODE)
REFERENCES DELIVERY_INFO (DELIVERY_INFO_CODE);




